name: openidea
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  path: ^1.8.0
  shared_preferences: ^2.0.15
  flutter_quill: ^10.4.9
  flutter_quill_extensions: ^10.5.0
  quill_delta: ^3.0.0-nullsafety.2
  flutter_colorpicker: ^1.1.0
  crypto: ^3.0.5
  flutter_gen: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_translation: ^0.20.0
  flutter_gen_runner: 5.7.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1

# This should be at the root level, not under 'flutter'
flutter_launcher_icons:
  image_path: assets/icon.png
  android: true
  ios: true
  remove_alpha_ios: true  # Add this line to remove alpha channel for iOS

flutter:
  generate: true
  uses-material-design: true
  
  fonts:
    - family: Kavivanar
      fonts:
        - asset: fonts/Kavivanar-Regular.ttf
  
  assets:
    - assets/icon.png